### ISSUE TITLE
Support for remote schema authentication but pull token from $ENV or .env or  similar?

### ISSUE THREAD

**Issue by hanleybrand** [jimkyndemeyer/graphql-config-examples#10]
I figured out how to authenticate to a remote endpoint that requires authentication, in my case...

```
      "Default GraphQL Endpoint": {
        "url": "https://remote.graphql.nd/api/graphql",
        "headers": {
          "user-agent": "JS GraphQL",
          "Authorization": "Bearer [supersecretsecret]"
```

...but I need to share my project in my organization and you know how people get about storing credentials in repos ;=)

Is it possible to use an auth header from a .env file or $ENV in the .graphqlconfig?

**Comment by jimkyndemeyer** [comment]
With https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/pull/426/files the plugin got support for `.env` files.

See the GitHub example for how to reference the variable:

https://github.com/jimkyndemeyer/graphql-config-examples/blob/b417cbc065f8dbcbbef83cb727b616976f731f7f/github-api-v4/.graphqlconfig#L9

See https://github.com/jimkyndemeyer/js-graphql-intellij-plugin#features-overview for the list of supported file names.
