### ISSUE TITLE
Any ways to make this get schema from the server?

### ISSUE THREAD

**Issue by Stevemoretz** [jimkyndemeyer/graphql-config-examples#11]
I love this plugin it's awesome, but can't get it to work with some types that are dynamically generated, it just works with .graphql files but that's not enough :(

Yes I can press this button and it does generate a file which fixes everything.

<img width="522" alt="Screen Shot 1401-09-13 at 21 30 07" src="https://user-images.githubusercontent.com/27680142/205507415-93f8854e-1d66-41b5-85b0-553614dda78c.png">

The problem is that after that file is generated my source schema files give duplicated errors all over the place.

<img width="511" alt="Screen Shot 1401-09-13 at 21 32 01" src="https://user-images.githubusercontent.com/27680142/205507524-7a080306-78b8-4220-9849-abe017af9166.png">

Is there any ways that I can make this work?

```
{
  "name": "Untitled GraphQL Schema",
  "schemaPath": "./schema.graphql",
  "extensions": {
    "endpoints": {
      "Default GraphQL Endpoint": {
        "url": "http://graphql.test/wp-json/central/api/graphql",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": true
      }
    }
  }
}

```

**Comment by jimkyndemeyer** [comment]
If you're authoring the schema and also doing queries against a modified/dynamic version of the schema in the same code base, you have to configure schema discovery to consider them as two isolated schemas. This will remove the "redefined Type" error you're seeing. See the docs at https://github.com/JetBrains/js-graphql-intellij-plugin#project-structure-and-schema-discovery and the mention of "Multi-schema projects".

**Comment by jimkyndemeyer** [comment]
So as an example, one config file is in your graphql server dir. The other config file is in your client dir, and that's where you generate your dynamic runtime schema using the green play button.

**Comment by Stevemoretz** [comment]
> So as an example, one config file is in your graphql server dir. The other config file is in your client dir, and that's where you generate your dynamic runtime schema using the green play button.

Thanks for responding but both my client and server are under the same project.

**Comment by jimkyndemeyer** [comment]
Are they also in the same folder? The config doesn't have to be in the project root.

**Comment by Stevemoretz** [comment]
> Are they also in the same folder? The config doesn't have to be in the project root.

Nope, they can be in different folders and the config is in the project root so that's the problem! Thank you so much for pointing me to the right direction, just got here still haven't read the link you provided in your first comment.

**Comment by Stevemoretz** [comment]
@jimkyndemeyer 

Could you give me a pointer my structure is like : 

My server files `wp-central/graphql/*.graphql` + `wp-central/*.graphql` and my client files can be anywhere else other than these two places, but they're also mostly inside `wp-central` couldn't make this work with multiple configs, so went with the project way:

```
{
  "name": "Untitled GraphQL Schema",
  "schemaPath": "./schema.graphql",
  "projects": {
    "server" : {
      "name": "server",
      "excludes": ["./wp-central/graphql-queries/**/*", "./schema.graphql"],
      "includes": ["./wp-central/graphql/**/*", "./wp-central/*.graphql"]
    },
    "client" : {
      "name" : "client",
      "includes": ["./wp-central/graphql-queries/**/*", "./schema.graphql"],
      "excludes": ["./wp-central/graphql/**/*", "./wp-central/*.graphql"]
    }
  },
  "extensions": {
    "endpoints": {
      "Default GraphQL Endpoint": {
        "url": "http://graphql.test/wp-json/central/api/graphql",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": true
      }
    }
  }
}
```

For easier implementation I limited client to just `./wp-central/graphql-queries` for now 

But I still get duplicate errors on server files, the client file at `./wp-central/graphql-queries` seems to be fine though.

**Comment by jimkyndemeyer** [comment]
I recall that any file in the `schemaPath` field is considered the main part of your schema even with excludes, and you have that at the root currently. You can try moving the `schemaPath`and `extensions` fields into your `client` project definition, and make sure you set the schema path to write the file where it's only included by the client project, e.g. in the `graphql-queries` sub folder. The server has no use of the introspected schema.graphql file, and would only consider the types as duplicates, if I understand your project setup correctly.

**Comment by Stevemoretz** [comment]
> I recall that any file in the `schemaPath` field is considered the main part of your schema even with excludes, and you have that at the root currently. You can try moving the `schemaPath`and `extensions` fields into your `client` project definition, and make sure you set the schema path to write the file where it's only included by the client project, e.g. in the `graphql-queries` sub folder. The server has no use of the introspected schema.graphql file, and would only consider the types as duplicates, if I understand your project setup correctly.

Thank you so much moving the file worked, you're the best!

**Comment by Stevemoretz** [comment]
@jimkyndemeyer Hi, sorry to bother you again. Just one last question, is there any way that autocompletion just works the way it does now but when we hold the ctrl button and click on the words (for jump to source action in IDE) instead of moving to the generated file it would go to the source files? Frankly that's the only thing in needs to be perfect! Loving this plugin so awesome!

**Comment by jimkyndemeyer** [comment]
That's not currently supported, but I could see the use case for this. It's a pretty big feature though, that might even affect the architecture of schema discovery. The plugin would have to understand the relationship between two separate schemas, and as in your case the runtime one has dynamic parts where there's no "source" to navigate to. It also affects things like validation (the duplicate types errors you got initially).

I suggest you log this as an improvement ticket in https://github.com/JetBrains/js-graphql-intellij-plugin such that it's on JetBrain's radar (they're maintaining and improving the plugin going forward).

**Comment by jimkyndemeyer** [comment]
That's not currently supported, but I could see the use case for this. It's a pretty big feature though, that might even affect the architecture of schema discovery. The plugin would have to understand the relationship between two separate schemas, and as in your case the runtime one has dynamic parts where there's no "source" to navigate to. It also affects things like validation (they duplicate types errors you got initially).

I suggest you log this as an improvement ticket in https://github.com/JetBrains/js-graphql-intellij-plugin such that it's on JetBrain's radar (they're maintaining end improving the plugin going forward).

**Comment by Stevemoretz** [comment]
> That's not currently supported, but I could see the use case for this. It's a pretty big feature though, that might even affect the architecture of schema discovery. The plugin would have to understand the relationship between two separate schemas, and as in your case the runtime one has dynamic parts where there's no "source" to navigate to. It also affects things like validation (the duplicate types errors you got initially).
> 
> I suggest you log this as an improvement ticket in https://github.com/JetBrains/js-graphql-intellij-plugin such that it's on JetBrain's radar (they're maintaining and improving the plugin going forward).

Thank you so much for the suggestion!
