### ISSUE TITLE
looking for an example with remote WSS and HTTP links

### ISSUE THREAD

**Issue by dohomi** [jimkyndemeyer/graphql-config-examples#2]
Hello,

I try to get autocompletion up and running on both, websocket and http connection.

I tried following:
```
{
  "schemaPath": "schema.graphql",
  "extensions": {
    "endpoints": {
      "Default Introspection Endpoint": {
        "url": "https://gql-api.myserver.com/v1/graphql",
        "subscription": {
          "url": "wss://gql-api.myserver.com/v1/graphql"
        },
        "introspect": true,
        "headers": {
          "user-agent": "JS GraphQL",
          }
      }
    }
  }
}
```
But I still don't see completion in subscriptions so far. Any idea what I am doing wrong in my setup?

**Comment by jimkyndemeyer** [comment]
Hi Dominic.

Thanks for using the plugin.

If I'm understanding you correctly, you already have a subscription type defined in your `schema.graphql` file by invoking an introspection query, but you don't see any completions, e.g. like the following:

![image](https://user-images.githubusercontent.com/15837712/64632612-ae885b00-d3f9-11e9-94ce-ffafcfedfe20.png)

Did you check for schema errors in the GraphQL tool?

**Comment by dohomi** [comment]
@jimkyndemeyer after restarting WS and re-inspect everything works. I think I had a typo somewhere inside my setup. Thanks for the swift response and for this nice plugin.
