### ISSUE TITLE
Schema Discovery?

### ISSUE THREAD

**Issue by VikR0001** [jimkyndemeyer/graphql-config-examples#4]
I have a schema named `schema.js` located at `imports/startup/server/api/schema.js`.  In the GraphQL tab I see "Schema discovery summary - schema is empty". When I double-click it, I have the option to search project-wide for the schema file. I entered `schema.js` in the dialog box, but it says "No matches found". 

How can I correct this?

<img width="1684" alt="Screen Shot 2020-05-10 at 12 15 24 PM" src="https://user-images.githubusercontent.com/10912958/81508263-f973ae80-92b7-11ea-8e2a-c939d9ecb9be.png">

**Comment by jimkyndemeyer** [comment]
Hi VikR0001,

Sorry for the delayed reply.

If you look in the example projects in this repo, schemas are discovered in one of three ways:

- Defined locally in the project using `.graphql` GraphQL files
- Or using GraphQL snippets inside gql/graphql tagged template files in .js/.ts files in the project, e.g. https://github.com/jimkyndemeyer/graphql-config-examples/tree/master/extend-client-fields-and-directives
- Or fetched from a remote GraphQL endpoint using introspection, e.g. https://github.com/jimkyndemeyer/graphql-config-examples/tree/master/remote-schema-introspection

For additional docs about how schema discovery works, please see https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/developer-guide

Regarding the search dialog you found in the GraphQL panel, that only searches schema types that have already been discovered.

For your use case, if you've defined the schema using JavaScript, the third option with introspection is the way the plugin can discover your schema types. The plugin itself is written in Java, and used for GraphQL endpoints projects written in many different programming languages, so introspection is the way to unify these use cases based on the GraphQL Specification for introspection queries.

Hope this clears things up. Let me know if you have additional questions.

Best regards
Jim.
