### ISSUE TITLE
schema.json

### ISSUE THREAD

**Issue by mrdunski** [jimkyndemeyer/graphql-config-examples#6]
Is there support for schema.json?

That format is used by Apollo. Since I can't make plugin work with it, the apollo example seems to be a bit misleading. Is there any workaround?

Thanks

**Comment by jimkyndemeyer** [comment]
Hi Patryk,

The `schemaPath` field in the config also accepts JSON files with introspection results:

https://github.com/jimkyndemeyer/graphql-config-examples/blob/c3851ed3e949cf64a39f76472412a317bc93388f/remote-schema-introspection/.graphqlconfig#L3

See https://github.com/kamilkisiela/graphql-config/tree/legacy#simplest-use-case
