### ISSUE TITLE
Replicate behaviour of Relay support in custom similar cases [Question]

### ISSUE THREAD

**Issue by pedrotambo** [jimkyndemeyer/graphql-config-examples#9]
Hi Jim,

just wanted to ask if there's a way to achieve the same behaviour of Relay support but for custom directivas.
For example:

```
type Something {
    name: String
}
type Query {
    all: SomethingCollection @collection (for: "Something")
}
```
So "SomethingCollection" is marked as an error, but as that type is created programatically program works. 

Thanks, 
Pedro.

**Comment by jimkyndemeyer** [comment]
Hi Pedro,

Thanks for using the plugin.

If you're using "framework types" such as directives or types they can be defined in one or more `.graphql` files in your project. The files just need to be within the folders where you've set up schema discovery, which is the entire project by default.

The built-in Relay support is essentially just a way for the plugin to automatically include https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/master/resources/META-INF/relay%20modern%20directives%20schema.graphql as part of the schema discovery process. You can use that file as inspiration for your own types. There's also an example for Apollo directives at https://github.com/jimkyndemeyer/graphql-config-examples/blob/b417cbc065f8dbcbbef83cb727b616976f731f7f/extend-client-fields-and-directives/client-schema-extensions.js

Best regards,
Jim
